import { getProject, updateProject } from "@/lib/store";
import { notFound } from "next/navigation";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Printer, FileText, Building, MapPin } from "lucide-react";
import CostEditor from "./cost-editor";
import { revalidatePath } from "next/cache";

export default async function ProjectDetailPage({
  params,
}: {
  params: { id: string };
}) {
  const project = await getProject(params.id);

  if (!project) {
    notFound();
  }

  async function saveCostItems(costItems: typeof project.costItems) {
    "use server";
    await updateProject(params.id, { costItems });
    revalidatePath(`/projects/${params.id}`);
  }

  return (
    <div className="p-4 md:p-8">
      <header className="flex flex-col md:flex-row items-start md:items-center justify-between mb-8 gap-4">
        <div>
          <h1 className="text-3xl font-bold font-headline truncate max-w-xl">
            Project: {project.client}
          </h1>
          <p className="text-muted-foreground flex items-center gap-2">
            <MapPin className="w-4 h-4" /> {project.address}
          </p>
        </div>
        <Button asChild>
          <Link href={`/projects/${params.id}/proposal`}>
            <Printer />
            View & Print Proposal
          </Link>
        </Button>
      </header>

      <main className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          <CostEditor initialCostItems={project.costItems} saveCostItems={saveCostItems} />
        </div>
        
        <aside className="space-y-8">
          <Card>
            <CardHeader>
              <CardTitle>Project Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
              <div className="flex justify-between">
                <span className="font-medium text-muted-foreground">Client</span>
                <span>{project.client}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium text-muted-foreground">Address</span>
                <span className="text-right">{project.address}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium text-muted-foreground">Sq. Footage</span>
                <Badge variant="secondary">{project.squareFootage.toLocaleString()} sq ft</Badge>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                AI-Generated Proposal
              </CardTitle>
              <CardDescription>
                This is the initial draft generated by AI.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="prose prose-sm dark:prose-invert max-w-none bg-muted/50 p-4 rounded-md h-96 overflow-auto whitespace-pre-wrap font-sans">
                {project.proposalDraft || "No proposal generated yet."}
              </div>
            </CardContent>
          </Card>
        </aside>
      </main>
    </div>
  );
}
